services:
  - type: web
    name: acit-portal
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn acit_portal.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        sync: false
    autoDeploy: true

databases:
  - name: acit-portal-db
    databaseName: acit_portal_db
    user: acit_portal_user
