# Generated by Django 4.2.23 on 2025-10-17 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stockrequest',
            old_name='date_requested',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='stockrequest',
            old_name='HOD',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='stockrequest',
            name='description',
        ),
        migrations.RemoveField(
            model_name='stockrequest',
            name='status',
        ),
        migrations.AddField(
            model_name='stockrequest',
            name='asset_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='stockrequest',
            name='date_of_requirement',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stockrequest',
            name='tentative_vendor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
