# Generated by Django 4.2.23 on 2025-10-17 18:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('requests_app', '0002_rename_date_requested_stockrequest_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=100)),
                ('asset_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tentative_vendor', models.CharField(blank=True, max_length=255, null=True)),
                ('required_by_date', models.DateField(verbose_name='Required By Date')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=10)),
                ('date_submitted', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='StockRequest',
        ),
    ]
